# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 21:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=35, verbose_name='answer to question')),
                ('is_true', models.BooleanField()),
            ],
            options={
                'db_table': 'education_answer_to_question',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='book name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('date_of_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of create')),
            ],
            options={
                'db_table': 'education_book',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='chapter name')),
                ('text', models.TextField(verbose_name='chapter text')),
                ('experience', models.IntegerField(default=0, verbose_name='normal experience')),
                ('date_of_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of create')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Book')),
            ],
            options={
                'db_table': 'education_book_chapter',
            },
        ),
        migrations.CreateModel(
            name='LevelOfComplexity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=35, verbose_name='name')),
                ('level', models.IntegerField(default=0, verbose_name='level')),
                ('lite_description', models.TextField(blank=True, default='', verbose_name='lite description')),
                ('full_description', models.TextField(blank=True, default='', verbose_name='full description')),
                ('normal_experience', models.IntegerField(default=0, verbose_name='normal experience')),
                ('extra_experience', models.IntegerField(default=0, verbose_name='extra experience')),
            ],
            options={
                'db_table': 'education_level_of_complexity',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='question text')),
                ('experience', models.IntegerField(default=0, verbose_name='experience')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Chapter')),
            ],
            options={
                'db_table': 'education_question',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='test name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('experience', models.IntegerField(default=0, verbose_name='experience')),
                ('date_of_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of create')),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='education.Chapter')),
            ],
            options={
                'db_table': 'education_test',
            },
        ),
        migrations.CreateModel(
            name='UserChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_reading', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of reading')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'education_user_chapter',
            },
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0, verbose_name='level')),
                ('experience_start_range', models.IntegerField(default=0, verbose_name='experience start range')),
                ('experience_end_range', models.IntegerField(default=0, verbose_name='experience end range')),
            ],
            options={
                'db_table': 'education_user_level',
            },
        ),
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_done', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of done')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'education_user_test',
            },
        ),
        migrations.AddField(
            model_name='test',
            name='users',
            field=models.ManyToManyField(through='education.UserTest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='tests',
            field=models.ManyToManyField(to='education.Test'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='users',
            field=models.ManyToManyField(through='education.UserChapter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Question'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='chapter',
            order_with_respect_to='book',
        ),
    ]
