# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTestDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Question')),
                ('user_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.UserTest')),
            ],
            options={
                'db_table': 'education_question_test_done',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='user_test_question_done',
            field=models.ManyToManyField(through='education.QuestionTestDone', to='education.UserTest'),
        ),
    ]
