# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 05:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20170512_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time',
            field=models.TimeField(default=datetime.time(0, 15), verbose_name='time'),
        ),
        migrations.AddField(
            model_name='usertest',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start time'),
        ),
    ]
