# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20170518_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontestdone',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='education.Answer'),
            preserve_default=False,
        ),
    ]
