# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_questiontestdone_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontestdone',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='education.Answer'),
        ),
    ]
