# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_auto_20170518_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='max_questions',
            field=models.IntegerField(default=0, verbose_name='maximum of questions'),
        ),
    ]
