# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_test_max_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontestdone',
            name='viewed',
            field=models.BooleanField(default=False, verbose_name='question viewed'),
        ),
    ]
